integrations:
  - name: nri-docker
    #env:
      # Enables fetching metrics from Docker API when running on a host with cgroups v2
      #USE_DOCKER_API: true
    when:
      feature: docker_enabled
      file_exists: /var/run/docker.sock
    interval: 15s
  # This configuration is no longer included in nri-ecs images.
  # it is kept for legacy reasons, but the new one is located in https://github.com/newrelic/nri-ecs
  - name: nri-docker
    when:
      feature: docker_enabled
      env_exists:
        FARGATE: "true"
    interval: 15s
